const $=id=>document.getElementById(id), api=window.OpsAPI, base='/api/map-workbench';
const initialTab=location.hash.slice(1)||'build';
let pointAsset=null;
let assets=[], tab='', viewer, viewerModule, generation=0, busy=false, mapping;
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function current(){return assets.find(row=>row.id===$('asset').value);}
function setBusy(value){busy=value;for(const id of ['process-button','mapping-start','mapping-save','mapping-stop'])$(id).disabled=value;updateMapping();}
function updateMapping(){if(!mapping)return;const real=mapping.connected&&mapping.source==='ros',lidar=!!mapping.lidar_ready,controller=!!mapping.controller_ready,navigationNodes=(mapping.navigation_nodes_active||[]).length>0,navigationStopped=mapping.navigation_state==='inactive'&&mapping.navigation_graph_readable===true&&!navigationNodes,confirmed=$('manual-push-confirmed').checked;const state=({unknown:'尚无反馈',idle:'空闲',starting:'启动中',mapping:'采集中',map_data_ready:'点云已就绪',saving:'保存中',rviz_livox_started:'雷达已恢复',mapping_stopped:'已停止'})[mapping.status]||mapping.status;$('mapping-start').disabled=busy||!real||!lidar||!controller||!navigationStopped||!confirmed||mapping.active;$('mapping-save').disabled=busy||!real||!mapping.active;$('mapping-stop').disabled=busy||!real||!mapping.active;const navigation=navigationNodes?'仍有导航节点运行':navigationStopped?'已停止':mapping.navigation_state==='active'?'服务运行中':'状态未知';$('mapping-state').textContent=`ROS桥接：${real?'已连接':'未连接'} · 雷达点云：${lidar?'实时':'无新数据'} · 建图控制器：${controller?'就绪':'未就绪'} · 导航：${navigation} · 建图：${state}`;}
async function refresh(preferred){const previous=preferred||$('asset').value;assets=await api.get(base+'/assets');$('asset').replaceChildren(new Option(assets.length?'请选择地图':'暂无地图',''),...assets.map(a=>new Option(a.id,a.id)));if(assets.some(a=>a.id===previous))$('asset').value=previous;await selected();}
async function selected(){const row=current();notice(row?'当前地图：'+row.id:'请选择地图，或开始采集新地图。');$('asset-detail').textContent=row?`${row.pcd?'PCD 已就绪':'无 PCD'} · ${row.grid?'PGM / YAML 已就绪':'无栅格'}${row.resolution?' · '+row.resolution+' m/像素':''}`:'同一地图统一管理点云与栅格';$('output').value=row?row.id+'_clean':'';await show(tab||'build',true);}
async function show(next,reload=false){if(!['build','point','grid','locate'].includes(next))next='build';if(tab===next&&!reload)return;tab=next;history.replaceState(null,'','#'+next);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===next)));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!=='panel-'+next);const row=current(),key=row?.id||'';generation++;const token=generation;
  if(next==='point'){try{viewerModule ||= import('./point-viewer.js');const mod=await viewerModule;viewer ||= mod.createViewer($('viewer'),text=>$('box-info').textContent=text);viewer.resize();if(pointAsset===key&&row?.pcd)return;pointAsset=null;viewer.clear();$('point-info').textContent='左键旋转 · 右键平移 · 滚轮缩放';$('viewer-empty').hidden=false;$('viewer-empty').textContent=row?.pcd?'加载点云…':'请选择含 PCD 的地图';if(row?.pcd){const blob=await api.download(base+'/file/pcd/'+encodeURIComponent(key));if(token!==generation)return;const buffer=await blob.arrayBuffer();if(token!==generation)return;const count=viewer.load(buffer);pointAsset=key;$('viewer-empty').hidden=true;$('point-info').textContent=`${count.toLocaleString()} 点 · 坐标保留原点`;} }catch(e){notice(e.message,true);$('viewer-empty').textContent='点云加载失败，请检查文件或浏览器 WebGL 支持';}}
  if(next==='grid'){if($('grid-frame').dataset.asset!==key){$('grid-frame').src=row?.grid?'src/components/process-map/handle_map.html?embedded=1&map='+encodeURIComponent(key):'about:blank';$('grid-frame').dataset.asset=key;}if(!row?.grid)notice('请选择含 PGM / YAML 的地图，或先从点云处理生成栅格。');}
  else if(next==='locate'&&$('locate-frame').dataset.asset!==key){$('locate-frame').src='localization.html?embedded=1&asset='+encodeURIComponent(key);$('locate-frame').dataset.asset=key;}
  else if(next==='build')await mappingStatus();
}
async function mappingStatus(){try{const wasActive=!!mapping?.active;mapping=await api.get(base+'/mapping');if(wasActive&&!mapping.active)$('manual-push-confirmed').checked=false;updateMapping();}catch(e){notice(e.message,true);}}
async function follow(job){setBusy(true);$('job-strip').hidden=false;localStorage.setItem('map-workbench-job',job.id);try{while(true){$('job-id').textContent=job.id;$('job-state').textContent=({queued:'等待处理',running:'处理中',success:'已完成',failed:'未完成'})[job.status]||job.status;$('job-message').textContent=job.message;if(job.status==='failed')throw new Error(job.message);if(job.status==='success'){localStorage.removeItem('map-workbench-job');const key=job.result?.asset?.id||job.result?.asset_id;await refresh(key);if(job.kind==='process'){await show('grid');notice('新地图已保存，可继续修图或进入定位应用。');}else if(job.kind==='mapping-save'){await show('point');notice('原始点云已保存，可继续裁剪与去噪。');}else notice(job.result?.message||'操作完成');break;}await new Promise(resolve=>setTimeout(resolve,1000));job=await api.get(base+'/jobs/'+job.id);}}catch(e){notice(e.message+'；可刷新页面重新查询任务状态。',true);if(job.status==='failed')localStorage.removeItem('map-workbench-job');}finally{setBusy(false);await mappingStatus();}}
async function run(path,data){if(busy)return;setBusy(true);try{await follow(await api.post(base+path,data));}catch(e){notice(e.message,true);setBusy(false);}}
$('process-form').onsubmit=e=>{e.preventDefault();if(!current()?.pcd||pointAsset!==current().id)return notice('请先选择地图并等待点云加载完成。',true);const params=viewer?.selection()||{};run('/process',{source:current().id,output:$('output').value.trim(),z_min:Number($('z-min').value),z_max:Number($('z-max').value),resolution:Number($('resolution').value),denoise:$('denoise').checked,radius:Number($('radius').value),neighbors:Number($('neighbors').value),...params});};
$('mapping-start').onclick=()=>{if(!$('manual-push-confirmed').checked)return notice('请先在现场确认底盘处于厂家允许的安全手动/自由轮状态，并可人工推行。',true);run('/mapping/start',{manual_push_confirmed:true});};$('manual-push-confirmed').onchange=updateMapping;$('mapping-form').onsubmit=e=>{e.preventDefault();if(!mapping?.active)return notice('请先开始采集，再保存点云。',true);run('/mapping/save',{name:$('mapping-name').value.trim()});};$('mapping-stop').onclick=()=>run('/mapping/stop');
$('asset').onchange=()=>selected().catch(e=>notice(e.message,true));$('refresh').onclick=()=>refresh().catch(e=>notice(e.message,true));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab).catch(e=>notice(e.message,true)));
$('fit').onclick=()=>viewer?.fit();$('clear-boxes').onclick=()=>viewer?.clearBoxes();document.querySelectorAll('[data-draw]').forEach(b=>b.onclick=()=>{viewer?.drawBox(b.dataset.draw);notice('已切换俯视：按住左键拖出矩形，松开完成选区。框选删除作用于所选 XY 区域内的点。');});
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===$('grid-frame').contentWindow&&e.data?.type==='map-saved'){refresh(e.data.id).then(()=>{$('locate-frame').removeAttribute('data-asset');notice('栅格保存成功。');}).catch(err=>notice(err.message,true));}});
await refresh(new URLSearchParams(location.search).get('map')).catch(e=>notice(e.message,true));await show(initialTab);
const pending=localStorage.getItem('map-workbench-job');if(pending)api.get(base+'/jobs/'+pending).then(follow).catch(e=>{notice(e.message,true);localStorage.removeItem('map-workbench-job');});
setInterval(()=>{if(tab==='build'&&!document.hidden)mappingStatus();},4000);
