---
float64 vehicle_mode
float64 navigation_mode
float64 robot_radius
float64 tool_radius
float64 safety_distance
float64 point_spacing
int8 clean_mode
bool enable_insertion
float64 local_origin_longitude
float64 local_origin_latitude
float64 speed_run
float64 speed_max
float64 speed_min
bool start_from_top
string current_map
bool show_image
float64 coverage_direction
float64 forword_dis
float64 l_propeller
float64 r_propeller
float64 dir_propeller
float64 init_propeller
float64 limit_w
float64 close_track
float64 angle_threshold
float64 vv_wk
float64 rotation
float64 wheel_base
int8 run_mode
